version: '2'

# Be sure to set these environment variables:
#  - INFLUXDB_ADMIN_USER
#  - INFLUXDB_ADMIN_PASSWORD
#  - INFLUXDB_DB
#  - INFLUXDB_USER
#  - INFLUXDB_USER_PASSWORD

services:

  influxdb:
    build: influxdb
    restart: on-failure
    volumes:
      - 'influxdb-data:/var/lib/influxdb'

  grafana:
    build: grafana
    depends_on:
      - influxdb
    ports:
      - '80:3000'
    restart: on-failure
    volumes:
      - 'grafana-data:/var/lib/grafana'

  dtoverlay-enviro-phat:
    build: dtoverlay
    command: apply_overlays enviro-phat
    privileged: true
    restart: no

  bmp280-sensor:
    build: telegraf
    depends_on:
      - influxdb
      - dtoverlay-enviro-phat
    environment:
      - 'TELEGRAF_EXEC_COMMAND=/collect/bmp280.sh'
    restart: on-failure

  ads1015-sensor:
    build: telegraf
    depends_on:
      - influxdb
      - dtoverlay-enviro-phat
    environment:
      - 'TELEGRAF_EXEC_COMMAND=/collect/ads1015.sh'
    restart: on-failure

volumes:
  influxdb-data:
  grafana-data:
